name: Deploy Files

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy file to output directory
        run: |
          New-Item -ItemType Directory -Force -Path J:/ArcMap_Main/python/test
          # Copy-Item -Path "Assignment Region to KMZ.py" -Destination J:/ArcMap_Main/python/test -Force
